behaviors:
  Encircle:
    trainer_type: poca                       # MultiAgent Posthumous Credit Assignment

    hyperparameters:
      batch_size: 512
      buffer_size: 100000                   # replay buffer
      learning_rate: 0.001
      learning_rate_schedule: constant
      beta: 0.001

    network_settings:                       # Config of the neural network
      normalize: false
      hidden_units: 128 
      num_layers: 3
      vis_encode_type: simple

    reward_signals:
      extrinsic:
        gamma: 0.9
        strength: 1.0

    keep_checkpoints: 5
    max_steps: 2000000
    time_horizon: 64
    summary_freq: 10000
    threaded: true
